language: python
sudo: false
dist: xenial
cache: pip
before_cache:
  - chown -R travis:travis $HOME/.cache/pip
stages:
  - style
  - test
matrix:
  include:
    - stage: style
      python: 3.6
      install:
        - pip install -r requirements-dev.txt
        - pip install -r doc/requirements.txt
      script:
        - make check
        - cd doc && make
    - stage: test
      python: 3.6
      install:
        - pip install --upgrade pip codecov
        - pip install .
      script:
        - coverage run --concurrency=multiprocessing -m pytest && coverage combine
  fast_finish: true
notifications:
  email: false
