name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Test package, style and doc
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: Install the package
        run: |
          python -m venv env
          source env/bin/activate
          $HOME/.poetry/bin/poetry install

      - name: Test the package style conventions
        run: |
          source env/bin/activate
          make check

      - name: Test the package and generate coverage report
        run: |
          source env/bin/activate
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Build the doc
        run: |
          source env/bin/activate
          cd doc
          make
